#ifndef TEST_HEADER
#define TEST_HEADER

// para test
#define ASCII_0 48
#define ASCII_9 57
#define VALOR_INVALIDO -1

/**
 estados y eventos para la fsm
*/
typedef enum estados {
    ST_CUALQUIERA,

    ST_EN_LINEA,

    ST_YENDOSE_POCO_POR_DERECHA,
    ST_YENDOSE_MUCHO_POR_DERECHA,
    ST_AFUERA_POR_DERECHA,
    ST_VOLVIENDO_POR_DERECHA,
    ST_VOLVIO_POR_DERECHA,

    ST_YENDOSE_POCO_POR_IZQUIERDA,
    ST_YENDOSE_MUCHO_POR_IZQUIERDA,
    ST_AFUERA_POR_IZQUIERDA,
    ST_VOLVIENDO_POR_IZQUIERDA,
    ST_VOLVIO_POR_IZQUIERDA,
    ST_MAX
} estados_t;
typedef enum eventos {
    EV_CUALQUIERA = 8,

    EV_SENSORES_NNN = 0,
    EV_SENSORES_NNB = 1,
    EV_SENSORES_NBN = 2,
    EV_SENSORES_NBB = 3,
    EV_SENSORES_BNN = 4,
    EV_SENSORES_BNB = 5,
    EV_SENSORES_BBN = 6,
    EV_SENSORES_BBB = 7
} eventos_t;

#endif
